.lib "cpuid.dll"
CPUid$():"kCPUid"
CPUextendedId$():"kCPUextendedId"
CPUbrand$():"kCPUbrand"
CPUfeatures$():"kCPUfeatures"
CPUmodel%():"kCPUmodel"
CPUfamily%():"kCPUfamily"
CPUsteppingId%():"kCPUsteppingId"
CPUl1cache%():"kCPUl1cache"
CPUl2cache%():"kCPUl2cache"
