[IDEal Project file]
<Settings>
 Version="1"
 Expanded="True"
 Icon=""
 MainFile="Game.bb"
 Compiler="Blitz3D TSS"
 CommandLine=""
</Settings>
<Folders>
</Folders>
<Files>
 AbsPath="\Source Code\Achievements_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Caps_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Deferred_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Devil_Particles_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Difficulty_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Effects_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Events_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Event_Scripts_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Game.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Graphics_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\INI_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Instances_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Items_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\KeyBinds_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Launcher_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Loading_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Main_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Map_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Map_Rooms_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Materials_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Math_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Menu_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\NPCs_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\NPCs_AI_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Particles_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Save_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Shaders_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Sky_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Sounds_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Strict_Functions_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Subtitles_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
 AbsPath="\Source Code\Texture_Cache_Core.bb" PrjFolder="" Line="0" Column="0" Tip="0" Visible="False"
</Files>
